### PR TITLE
fix(storage): prevent FilePreviewDialog content and actions from overflowing dialog

### LINKED ISSUE #884: [1 point][Bug]: FilePreviewDialog layout overflows dialog bounds
### What's the bug?

`FilePreviewDialog` has a broken layout: action buttons overflow out of the dialog, preview content can overflow as well, and the overall dialog sizing does not adapt cleanly to viewport height.

Current implementation details in `frontend/src/features/storage/components/FilePreviewDialog.tsx`:
- The dialog wraps an inner container with fixed width/height constraints: `w-[800px] min-h-[500px] max-h-[820px]`
- Some preview modes also use fixed internal heights, for example PDF preview uses `h-[602px]`
- The preview region and footer actions are laid out inside that fixed shell, which can cause content and buttons to overflow instead of fitting inside the available dialog region
- The dialog does not appear to consistently cap itself against viewport height, so tall content can exceed the page height

Expected behavior:
- dialog width should stay constant
- dialog content should fit inside the dialog region instead of overflowing it
- preview area should adapt its width/height within the available space
- media preview should preserve aspect ratio
- dialog should have a maximum height so it never exceeds the page height
- footer buttons should stay inside the dialog bounds

### How to reproduce

1. Open Storage and preview files using `FilePreviewDialog`
2. Try previewing different file types, especially large images, PDFs, or other content with substantial intrinsic size
3. Observe that the buttons can overflow outside the dialog and the preview content can overflow as well
4. Resize the viewport smaller/taller and notice the dialog does not fit the available page height cleanly

### Environment (optional)

Frontend storage preview dialog in the current repo. The issue is in the layout/sizing behavior of `frontend/src/features/storage/components/FilePreviewDialog.tsx`.

### PR DESCRIPTION
**Pull request by adi-rajput**
Closes #884

## Summary

This PR fixes layout issues in `FilePreviewDialog` where preview content and action buttons could overflow outside the dialog.

The issue was caused by fixed height constraints such as:
- `min-h-[500px]`
- `max-h-[820px]`
- fixed preview heights like `h-[602px]`

These constraints prevented the dialog from adapting to viewport height and caused overflow when previewing large media.

### Changes
- Replaced fixed height layout with a flex-based column layout
- Added viewport constraint using `max-h-[90vh]`
- Made the preview area flexible and scrollable using `flex-1 min-h-0 overflow-auto`
- Ensured footer actions remain inside the dialog using `shrink-0`
- Removed fixed preview heights to allow responsive resizing
- Ensured preview media maintains aspect ratio using `max-h-full max-w-full object-contain`

### Result
- Dialog width remains constant
- Dialog height adapts to viewport
- Large preview content scrolls instead of overflowing
- Footer buttons remain inside dialog bounds

---

## How did you test this change?

I tested the fix locally using the development environment.

Steps performed:

1. Started the project using `docker compose up`
2. Logged into the admin dashboard
3. Created a storage bucket and uploaded files
4. Opened the preview dialog for different file types

Test cases verified:

- Large image preview
- PDF preview
- Smaller browser viewport

Expected results were confirmed:
- Dialog height stays within viewport
- Preview content scrolls instead of overflowing
- Footer action buttons remain visible inside the dialog

[Screencast from 2026-03-15 12-42-49.webm](https://github.com/user-attachments/assets/ad83dc22-ec47-430c-a5ca-f3ed3b799513)

## Summary by CodeRabbit

* **New Features**
  * Inline error UI in the preview area with Download, Open in new tab, and Close actions; header shows file name, size, and type.

* **Style**
  * Improved video scaling to preserve aspect ratio.
  * PDF/iframe and dialog layouts updated for full-height, responsive fitting.
  * Button group wraps with consistent minimum widths for small viewports; action labels adjusted for wrapping.

* **Bug Fixes**
  * Loading and preview containers now fill available space while keeping centered indicators.

### CODE REVIEW

**Comment by adi-rajput** [comment]
@Fermionic-Lyu Review this, if the suggested change is actionable then I am happy to implement it !!

**Comment by Fermionic-Lyu** [comment]
> @Fermionic-Lyu Review this, if the suggested change is actionable then I am happy to implement it !!

Yeah, I think the code rabbit comment is worth addressing. Kindly implement it, thanks!

**Comment by adi-rajput** [comment]
Okay going to implement that.

**Comment by adi-rajput** [comment]
Summary: Show a visible error panel in FilePreviewDialog (alert text + Download/Open/Close actions) so failed previews aren’t blank.
Testing: Not run (manual repro by previewing a stale/missing storage file).

Screenshot from 2026-03-15 14-32-10

**Comment by adi-rajput** [comment]
@Fermionic-Lyu Review the changes and please tell if any other changes or improvements are required

File: frontend/src/features/storage/components/FilePreviewDialog.tsx [hunk 1]
```diff
@@ -216,30 +216,67 @@ export function FilePreviewDialog({ open, onOpenChange, file, bucket }: FilePrev
...
+              <div
+                className="flex w-full h-full items-center justify-center rounded bg-neutral-100 dark:bg-neutral-700 px-4"
+                role="alert"
+                aria-live="polite"
+              >
+                <div className="flex max-w-lg flex-col items-center gap-3 text-center">
+                  <p className="text-sm text-zinc-600 dark:text-neutral-200">
+                    {error}. Please try again, or use Download / Open in new tab.
+                  </p>
+                  <div className="flex flex-wrap justify-center gap-3">
```
Comment (Fermionic-Lyu) [inline frontend/src/features/storage/components/FilePreviewDialog.tsx]: I think the action buttons here are duplicate. Let's remove them and keep the error state clean

File: frontend/src/features/storage/components/FilePreviewDialog.tsx [hunk 2]
```diff
@@ -216,30 +216,67 @@ export function FilePreviewDialog({ open, onOpenChange, file, bucket }: FilePrev
...
               </div>
+            ) : error ? (
+              <div
+                className="flex w-full h-full items-center justify-center rounded bg-neutral-100 dark:bg-neutral-700 px-4"
+                role="alert"
+                aria-live="polite"
+              >
+                <div className="flex max-w-lg flex-col items-center gap-3 text-center">
+                  <p className="text-sm text-zinc-600 dark:text-neutral-200">
+                    {error}. Please try again, or use Download / Open in new tab.
```
Comment (Fermionic-Lyu) [inline frontend/src/features/storage/components/FilePreviewDialog.tsx]: Just render the error message should be good

**Comment by adi-rajput** [comment]
Screenshot from 2026-03-15 23-00-31

Just rendering the error message.

**Comment by adi-rajput** [comment]
@Fermionic-Lyu review this .

**Comment by Fermionic-Lyu** [comment]
1 point -> adi-rajput
