### PR TITLE
[Fix] Fix edit table functionalities

### LINKED ISSUE #15: [Feat][Backend] Support edit table with unique value, nullable, default value
We currently don't have edit column capability with specifying unique, nullable, and default value

### PR DESCRIPTION
**Pull request by Fermionic-Lyu**
https://github.com/user-attachments/assets/fd133a47-a7d2-4a87-80f1-d3b7bd62d0b3

Can't upload video > 10Mb so only demo the key features.

1. Forbids toggling Nullable & Unique constraints on existing columns;
2. Default value is now working;
3. Now supports editing table name;
4. Re-designed updateTableSchemaRequest schema;
5. Updated docs, tests & mcp accordingly

Partially resolves #15 .

### CODE REVIEW

File: backend/src/controllers/TablesController.ts [hunk 1]
```diff
@@ -648,108 +743,108 @@ export class TablesController {
...
-            `Column(${newName}) already exists. Please check the schema with GET /api/database/tables/${table}/schema endpoint.`
-          );
-        }
-        // Simulate the rename
-        workingColumnSet.delete(oldName);
-        workingColumnSet.add(newName as string);
-      }
-    }
-  }
+  // private validateTableOperations(
```
Comment (Fermionic-Lyu) [inline backend/src/controllers/TablesController.ts]: This function is commented out because if we have a correct operation sequence (dropFK -> dropCol -> updateCol -> addCol -> addFK), then there won't be operation conflicts (operation will still FAIL if it's violating DB constraints, just no conflict with other operations)

File: shared-schemas/src/database-api.schema.ts [hunk 2]
```diff
@@ -23,59 +23,47 @@ export const createTableResponseSchema = tableSchema
...
+      newTableName: z
+        .string()
+        .min(1, 'New table name cannot be empty')
+        .max(64, 'New table name must be less than 64 characters'),
+    })
+    .optional(),
 });
 
-// Full schema with refinement - for validation
-export const updateTableSchemaRequest = updateTableSchemaBase.refine(
```
Comment (Fermionic-Lyu) [inline shared-schemas/src/database-api.schema.ts:66]: The refine is removed because there is no harm to pass empty operations to this endpoint. It will just simply skip every check and return 'update success' because there is nothing to update

File: backend/src/controllers/TablesController.ts (hunk 1 above)
Comment (Fermionic-Lyu) [reply backend/src/controllers/TablesController.ts]: But we may still need it in the future, for COMMIT/ROLLBACK purposes

File: backend/src/controllers/TablesController.ts [hunk 3]
```diff
@@ -357,47 +382,112 @@ export class TablesController {
...
+          } else {
+            // Set default
+            await db
+              .prepare(
+                `
+                ALTER TABLE ${safeTableName} 
+                ALTER COLUMN ${this.quoteIdentifier(column.columnName)} SET DEFAULT '${column.defaultValue}'
+              `
+              )
+              .exec();
```
[the remark this answers is not in the document]
Comment (Fermionic-Lyu) [reply backend/src/controllers/TablesController.ts:450]: True but this is just following the current design. We may need to revisit the SQL injection risk in the future and fix everything together in one PR

File: backend/src/controllers/TablesController.ts [hunk 4]
```diff
@@ -357,47 +382,112 @@ export class TablesController {
...
-        `
-          SELECT column_name FROM information_schema.columns
-          WHERE table_schema = 'public' AND table_name = ?
-        `
-      )
-      .all(table);
-    const columnSet = new Set(tableColumns.map((c: { column_name: string }) => c.column_name));
+    const safeTableName = this.quoteIdentifier(tableName);
+
+    // const tableColumns = await db
```
Comment (tonychang04) [inline backend/src/controllers/TablesController.ts]: why did we choose to comment out instead of deleting?

edit: nvm sall that we may need to commit/rollback hmm let me think

Comment (Fermionic-Lyu) [reply backend/src/controllers/TablesController.ts]: Same reason as below, thought we may need this logic in the future for COMMIT/ROLLBACK design. We could delete it now and re-implement in the future with a more robust deisign too. Let me know what you think it's better

File: backend/src/controllers/TablesController.ts [hunk 5]
```diff
@@ -479,23 +546,51 @@ export class TablesController {
...
+            SELECT EXISTS (
+              SELECT FROM information_schema.tables
+              WHERE table_schema = 'public'
+              AND table_name = ?
+            ) as exists
+          `
+        )
+        .get(safeNewTableName);
+
+      if (tableExists?.exists) {
```
Comment (tonychang04) [inline backend/src/controllers/TablesController.ts]: Do we need to do this check? if pgsql is renaming a table name to an existing table name, I think pgsql will throw an error itself?

Comment (Fermionic-Lyu) [reply backend/src/controllers/TablesController.ts]: That's right, should remove this check

File: backend/src/controllers/TablesController.ts (hunk 4 above)
Comment (tonychang04) [reply backend/src/controllers/TablesController.ts]: I'm not fully understanding the intention here 🤔

My idea for commit rollback. is to start a commit at the beginning 
then big try catch all the operations

if ever catched an error. we trigger rollback?  We let pg sql do the database checks itself, we only throw additional validation error only because we need to suit our unique system

Comment (Fermionic-Lyu) [reply backend/src/controllers/TablesController.ts]: Yeah I think this logic was introduced to our code base weeks ago, when you were solving the conflict of renaming a column into a column that is dropped at the same time.

The idea here is to simulate the updateSchema operation first, and only perform the full operation list if everything pass. If one fails, the simulation fails and we don't perform the request at all.

In the future, I think a more straight forward way is to use the built-in commit/rollback SQL queries in pgdb directly. And we have to consider metadata syncing as well. We will run into BIG troubles if the updateSchema request succeed but metadata is not updated or vice versa.

Comment (tonychang04) [reply backend/src/controllers/TablesController.ts]: >  straight forward way is to use the built-in commit/rollback SQL queries in pgdb directly.

 This ++. I was suggesting this as well.

 Previously we are doing lots of unnecessary pre-validations where pgsql can throw the error itself then we can use it's default rollback. 

Also metadata sync, it's not tricky(yet). Since right now `updateDatabaseMetadata` reads the entre database again and outputs it to metadata. instead of step by step. So after operation completed we call updateDatabaseMetadata
:). This needs to be revisted as it's wasteful. But it's bullet proof now.

Comment (Fermionic-Lyu) [reply backend/src/controllers/TablesController.ts]: I'll remove this commented code then.

Comment (tonychang04) [reply backend/src/controllers/TablesController.ts]: Yup! Thanks!

**Review by tonychang04 — APPROVED** [review]
Other changes LGTM!

lets merge it and see it becoming cleaner and better! 
Will also file a issue to support rollback and commmit, should be pretty quick
