### PR TITLE
fix(frontend): add missing DialogDescription for dialog accessibility

### LINKED ISSUE #861: [1 point][Bug]: Fix missing DialogContent description / aria-describedby warning
### What's the bug?

Opening some dialogs triggers the warning:

`Warning: Missing \`Description\` or \`aria-describedby={undefined}\` for {DialogContent}.`

This looks like an accessibility/composition issue in how `DialogContent` is being used rather than a single dialog-specific problem.

A quick scan shows multiple places using `DialogContent` without an obvious `DialogDescription`, for example:
- `frontend/src/features/auth/components/OAuthConfigDialog.tsx`
- `frontend/src/features/auth/components/UserFormDialog.tsx`
- `frontend/src/features/database/components/RecordFormDialog.tsx`
- `frontend/src/features/functions/components/ScheduleFormDialog.tsx`
- `frontend/src/features/realtime/components/ChannelFormDialog.tsx`
- `frontend/src/components/PromptDialog.tsx`
- `frontend/src/features/storage/components/FilePreviewDialog.tsx`

Some dialogs already include `DialogDescription` correctly (for example `BucketFormDialog` and `ForeignKeyPopover`), so the bug likely comes from inconsistent usage of the shared dialog primitives from `@insforge/ui`.

Expected behavior:
- opening dialogs should not emit this accessibility warning
- dialogs should provide a valid description or intentionally opt out with the correct `aria-describedby` handling
- the fix should be applied consistently across the dialog patterns that use the shared primitives

### How to reproduce

1. Open the app and navigate to any page that launches one of the affected dialogs
2. Open a dialog such as OAuth config, add user, record form, schedule form, prompt dialog, or similar
3. Check the browser console
4. Observe the warning: `Missing Description or aria-describedby={undefined} for {DialogContent}`

### Environment (optional)

Frontend app using the shared `@insforge/ui` dialog primitives in the current repo. The warning appears in browser console when dialog content mounts.

### PR DESCRIPTION
**Pull request by babuClawd**
## Summary
This PR fixes the Radix warning:

`Missing Description or aria-describedby={undefined} for {DialogContent}`

by adding missing `DialogDescription` / `MenuDialogDescription` across affected dialog call sites in `frontend/src`.

## What changed
- Added screen-reader-only descriptions (`className="sr-only"`) to dialog components that used `DialogContent` without a description
- Added `MenuDialogDescription` primitive to the UI package (`ui/src/components/MenuDialog.tsx`) and exported it
- Applied fixes consistently across all previously missing dialog call sites (17 frontend files)

## Reviewer feedback from prior PR addressed
- Avoided visible duplicate header in `FilePreviewDialog` by making `DialogTitle` sr-only while preserving existing visible `<h2>` header
- Reduced duplicate menu dialog descriptions in `AuthSettingsMenuDialog` (kept a single contextual description)

## Validation
- Re-scanned frontend `DialogContent` usages: no remaining call sites missing `DialogDescription` / `aria-describedby`
- Ran Prettier check on all touched files: pass

Fixes #861

## Summary by CodeRabbit

* **Accessibility**
  * Improved dialog accessibility across the app by adding screen‑reader‑only titles and descriptions to many dialogs, enhancing compatibility with assistive technologies without changing visible UI or behavior.

* **New Features**
  * Added a standardized MenuDialogDescription component to the UI library to unify semantic dialog description markup for better accessibility.

### CODE REVIEW

**Comment by babuClawd** [comment]
Addressed CodeRabbit’s duplicate-announcement suggestion and tightened accessibility consistency:

- `frontend/src/components/PromptDialog.tsx`: kept `DialogDescription` as the aria source and marked the visible subtitle paragraph as `aria-hidden="true"` to avoid double screen-reader announcement.
- `frontend/src/features/dashboard/components/PromptDialog.tsx`: applied the same pattern proactively for consistency (sr-only description + visible subtitle hidden from SR).

Also reconfirmed the original issue scope:
- all previously missing `DialogContent` / `MenuDialogContent` descriptions are covered
- prior PR #864 reviewer blockers are addressed (no duplicate visible header in FilePreviewDialog; missed dialog call sites covered)

Happy to adjust if you prefer `aria-describedby` targeting the visible paragraph instead.

File: frontend/src/features/storage/components/FilePreviewDialog.tsx [hunk 1]
```diff
@@ -199,6 +206,10 @@ export function FilePreviewDialog({ open, onOpenChange, file, bucket }: FilePrev
   return (
     <Dialog open={open} onOpenChange={onOpenChange}>
       <DialogContent className="p-0 w-[800px] max-w-[calc(100vw-2rem)] h-[min(820px,calc(100vh-2rem))] max-h-[calc(100vh-2rem)]">
+        <DialogHeader>
```
Comment (Fermionic-Lyu) [inline frontend/src/features/storage/components/FilePreviewDialog.tsx]: Seems like this header introduced an unwanted region in the file preview dialog. Please investigate it

Comment (babuClawd) [reply frontend/src/features/storage/components/FilePreviewDialog.tsx]: Good catch — you were right. `DialogHeader` was introducing extra layout (padding/border), which created that unwanted region. I removed the `DialogHeader` wrapper and kept `DialogTitle` + `DialogDescription` as `sr-only` directly under `DialogContent`, so accessibility remains intact without changing visual layout. Fixed in fb2d232b.

**Review by Fermionic-Lyu — APPROVED** [review]
LGTM
