### PR TITLE
fix/ui-scroll

### LINKED ISSUE #685: [Bug]: UI Scroll issue
### What's the bug?

**UI Scroll issues in 14 inch screens**

- Sidebar is not scrollable
- In tables page, before creating any table - the templates are not scrollable.

### How to reproduce

1. Open Dashboard page, scroll sidebar

Image
 
2. Select Tables on sidebar, when there are no tables, while creating a table there are templates available but not scrollable to see all the templates.

Image

 

### Environment (optional)

OS - Windows
Browser - Microsoft Edge

### PR DESCRIPTION
**Pull request by p1kalys**
Fixes #685

## Summary

- Added tailwind-scrollbar dependency
- Updated styles for scrollable components in sidebar and tables page to fix scrolling

## How did you test this change?
**Sidebar**

https://github.com/user-attachments/assets/4270358d-573e-4560-9ad5-5d825d26bb69

**Tables Page**

https://github.com/user-attachments/assets/116df2d2-f559-4e9b-b426-cc5ba898aa48

## Summary by CodeRabbit

* **Style**
  * Added a refined, thinner scrollbar for improved visual consistency and a cleaner UI.

* **Bug Fixes**
  * Enabled vertical scrolling in the top navigation menu to keep items accessible when long.
  * Enabled vertical scrolling in the empty tables view to improve content handling on smaller screens.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: frontend/src/components/layout/PrimaryMenu.tsx [hunk 1]
```diff
@@ -138,7 +138,7 @@ export function PrimaryMenu({
         )}
       >
         {/* Top navigation items with separators */}
-        <nav className="flex flex-col gap-2">
+        <nav className="flex flex-col gap-2 overflow-y-auto scrollbar-thin scrollbar-track-transparent [&::-webkit-scrollbar-button]:hidden">
```
Comment (Leo-rq-yu) [inline frontend/src/components/layout/PrimaryMenu.tsx]: I believe this is the only place where the new package is being used, right? I wonder if you can try to remove the new package and use raw css in the index.css to achieve the same effect?

**Review by Leo-rq-yu — COMMENTED** [review]
Hello @p1kalys  . Really appreciate your fixing.

File: frontend/src/components/layout/PrimaryMenu.tsx (hunk 1 above)
Comment (p1kalys) [reply frontend/src/components/layout/PrimaryMenu.tsx]: Sure, will try that

**Comment by tonychang04** [comment]
@p1kalys let me know if you can address the linter! and we are good to go!

**Comment by tonychang04** [comment]
https://discord.gg/JJFmcAsS also feel free to join our discord for faster response and reviews!

**Comment by p1kalys** [comment]
Thanks @tonychang04  and @Leo-rq-yu for the review. I have updated the formatting too. Looking forward to contribute more.

**Comment by Leo-rq-yu** [comment]
> Thanks @tonychang04 and @Leo-rq-yu for the review. I have updated the formatting too. Looking forward to contribute more.

Looks good. You can merge the PR now. Thx!
