### PR TITLE
FIX : Single toast for bulk deletion in object storage. 

### LINKED ISSUE #471: [Bug]: Multiple toast while deleting bucket files.
### What's the bug?

Multiple toast are displayed when doing the bulk deletion of the files inside the bucket. We have to modify it to a single toast for better UX. 

Image

### How to reproduce

1. create multiple files in the bucket
2. select more than one bucket
3. click on delete option 

After deleting multiple toast of successful deletion is showed. 

### Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by Abiji-2020**
## Summary

This PR fixes #471 

It modifies the mutation to do the bulk deletion inside of it, and then shows the single toast after doing the bulk deletion 

## How did you test this change?

I have tested it manually.

image

## Summary by CodeRabbit

* **New Features**
  * Bulk file deletion: delete multiple files in a single action (UI now calls bulk deletion).
  * Improved deletion feedback: contextual toasts for full success, partial failures, or complete failure, with aggregated success/failure counts.
  * Single-file deletion preserved via the bulk flow.
  * Selection cleared after deletion and list cache is refreshed to reflect changes.

### CODE REVIEW

File: frontend/src/features/storage/hooks/useStorage.ts [hunk 1]
```diff
@@ -103,11 +103,30 @@ export function useStorage() {
 
   // Mutation to delete an object
   const deleteObjectMutation = useMutation({
```
Comment (Fermionic-Lyu) [inline frontend/src/features/storage/hooks/useStorage.ts]: This mutation should be deleteObjectsMutation after your change

**Comment by Abiji-2020** [comment]
The CI needs to re-run as the failing is due to the Actions are unable to access the docker service now.

**Review by Fermionic-Lyu — APPROVED** [review]
Changes LGTM!
